name: Build to Gist
on: 
  push:
    branches: [ dev ]
  schedule:
    - cron:  '0 6 * * *'
  workflow_dispatch:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update jms.ini file
      run: |
        echo "url=${{ secrets.URL }}" >> replacements/profiles/jms.ini
    - name: Build Docker image
      run: docker build -t my-image .
    - name: Run command
      run: docker run --rm -v "$(pwd)"/output:/base/output my-image subconverter -g
    - name: Upload to gist
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |
          const fs = require('fs');
          const gistId = process.env.GIST_ID;
          const content = fs.readFileSync('output/jms.yaml', 'utf8');
          const gists = github.gists;
          const files = {
            'jms.yaml': { content: content }
          };

          await gists.update({ gist_id: gistId, files: files });
      env:
        GIST_ID: ${{ secrets.GIST_ID }}
